### ISSUE TITLE
URL Display Incorrectly in Address Bar

### ISSUE THREAD

**Issue by divrisk** [divrisk/WebsiteNew#2]
For an example,

personal page I have <link rel="canonical" href="http://www.divrisk.com/personal">, but it only shows www.divrisk.com in url.

**Comment by hadfield** [comment]
it looks like you are loading all the pages inside an iframe.  if you remove the iframe so the pages are at the "top" level then the urls should appear in the url bar.

**Comment by hadfield** [comment]
we can also fix it so that the github page is at the main domain by updating the DNS settings and using the CNAME option in github for this.  i can assist.  it's potentially a good time to move the domain name over to aws.

**Comment by divrisk** [comment]
Gotcha, i thought of that but was not sure if because of that. Since our domain is still on 1&1, i did the frame direct through it. So i guess we should figure out the aws plan then all of the url and certificate should be easily resolved.

**Comment by hadfield** [comment]
yup!  i figured you had the iframe there to hide the github links.
