### ISSUE TITLE
URL Pattern

### ISSUE THREAD

**Issue by hadfield** [divrisk/WebsiteNew#3]
Something like:

divrisk.com/456/CommercialInsurance/GeneralLiability/GeneralLiability.html

this is mainly for SEO purposes to put these keywords into the URLs.  the "456" is a unique number specific to General Liability which allows us to switch around the keywords but still know that the page is the general liability one.

we would add something like:
divrisk.com/456/CommercialInsurance/GeneralLiability/GeneralLiability.html?form=open&ad=987...

the "form=open&ad=987..." part would be used as the landing page for the ad so that the javascript in the page would know to open the form and know the identifier of the ad "campaign" so we can compare campaign vs campaign (i.e. multiple ads running for general liability, etc.)

**Comment by divrisk** [comment]
awesome, i will add those links' format in the script.
